### ISSUE TITLE
数据集包损坏

### ISSUE THREAD

**Issue by sunyilgdx** [ShengdingHu/KnowledgeablePromptTuning#1]
同学您好，感谢您开源项目，我想将这几个英文数据集在我的模型上测试一下，目前IMDB的数据集下载后解压出现问题，可否再上传一下。另外本文中是否设置了验证集进行模板或超参数的调整？

**Comment by ShengdingHu** [comment]
您好，感谢您指出，已经重新上传IMDB数据集。本文中zero-shot实验未进行超参数的选择，但是根据基线模型在测试集上的性能选了4个人工模板（这样做主要因为我们重点不在模板上，所以选出合理性能的模板之后，就在同样的模板上我们的模型进行对比）, 的确模板的选择对性能有较大影响，我们也将各模板性能放在了附录中，如您要进行对比，可以使用相同的模板，或者将您的模板配合上我们的代码进行评测。few-shot实验中用了验证集进行了label words 权重的更新学习率的选择，其他参数例如大模型的学习率等未进行调整，使用的是pet中默认的一些参数。

**Comment by sunyilgdx** [comment]
十分感谢
