### ISSUE TITLE
There is no  YahooAnswersTopicsProcessor

### ISSUE THREAD

**Issue by znsoftm** [ShengdingHu/KnowledgeablePromptTuning#10]
Please correct it.

In the up-to-date version of openpromt, there is no  YahooAnswersTopicsProcessor.

**Comment by ShengdingHu** [comment]
I think it's already [here](https://github.com/thunlp/OpenPrompt/blob/main/openprompt/data_utils/huggingface_dataset.py#L222)? What bugs did you encounter specifically?

**Comment by znsoftm** [comment]
I get the code from github. So is it not  merged into main stream ?
