### ISSUE TITLE
运行fewshot.py出现错误

### ISSUE THREAD

**Issue by qinglongheu** [ShengdingHu/KnowledgeablePromptTuning#17]
OSError: Can't load the configuration of '../plm_cache/roberta-large'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '../plm_cache/roberta-large' is the correct path to a directory containing a config.json file

**Comment by ShengdingHu** [comment]
This path is my local cache of the roberta-large. Please use your local path of the roberta-large model, or just use 'roberta-large' to let the huggingface download it for you.
