### ISSUE TITLE
学术探讨

### ISSUE THREAD

**Issue by sunyilgdx** [ShengdingHu/KnowledgeablePromptTuning#2]
同学你好，我想请教一个问题，引入外部知识的话，如果不借助知识库自动引入，只靠人工总结（比如说我自己根据经验总结一些同义词），这样可以吗，会不会不具备学术性

**Comment by ShengdingHu** [comment]
应该是可以的，虽然可能人工总结会有主观性和偏差，但是直觉上效果可能会不错。
