### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xiao432** [ShengdingHu/KnowledgeablePromptTuning#7]
我下载解压roberta-large,但是依然提示:
OSError: ../plm_cache/roberta-large is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by ShengdingHu** [comment]
您好！这个路径是我本地存放roberta-large的路径，你需要更改成你自己存放roberta-large的路径，或者如果你的服务器网络连接通畅，可以直接改成“roberta-large”来从huggingface上下载
