### ISSUE TITLE
在运行代码时，提示没有manual_template.txt文件？

### ISSUE THREAD

**Issue by Hou-jing** [ShengdingHu/KnowledgeablePromptTuning#8]
请问，我使用openprompt下载数据后，并没有manual_template.txt文件，您们能否提供下呢？或者我应该在哪里找到这个文件呢？
![image](https://user-images.githubusercontent.com/75936962/169760131-3e4626cc-6144-49db-b377-17b91e450e84.png)

**Comment by Hou-jing** [comment]
对不起，我想我解决这个问题，这些文件了，他们在openprompt中

**Comment by Hou-jing** [comment]
我想，我解决这个问题了，这些文件我在openprompt中找到了

**Comment by ShengdingHu** [comment]
谢谢使用!
